import './components/tag';
import './components/ripple';
import './components/button';
import './components/circular-progress';
import './components/dialog';
import './components/paper';
import './components/skeleton';
import './components/mask';
import './components/drawer';
import './components/message';
import './components/radio';
import './components/rate'